version: '3.8'

services:
  backend:
    build: .
    container_name: gsb_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gsb_ecommerce?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - gsb-network

  db:
    image: mysql:8
    container_name: gsb_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsb_db_ecommerce
    ports:
      - "3306:3306"
    networks:
      - gsb-network

networks:
  gsb-network:
    driver: bridge
