spring:
  datasource:
    url: jdbc:mysql://localhost:3307/gsb_db_ecommerce
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: password

  main:
    allow-circular-references: true
#    logging:
#        level: DEBUG


